Add ermar quote long awaited feature, the good one
Horgix/elsa pull request #10
Opened 2017-09-26 13:37 UTC by wedjats

2017-10-03 12:26 UTC, wedjats commented
someone here ?

2017-10-09 09:20 UTC, Horgix requested changes

2017-10-09 09:20 UTC, Horgix commented on elsa.py
> +            u"Ecoute, moi j'aime l'amour.",
I think this one is a duplicate of 2 lines above

2017-10-09 12:12 UTC, wedjats commented
Changements effectués.

2017-12-15 10:47 UTC, merged